### ISSUE TITLE
Johto Mode doesn't seem to work

### ISSUE THREAD

**Issue by pokemonfan1937** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#11] opened 2021-06-01 21:59 UTC
Attempting to randomize using Johto Only mode results in this error:

Traceback (most recent call last): File "RunGUI.py", line 91, in runRandomizer File "RunCustomRandomizationAssumedFill.py", line 26, in randomizeRom TypeError: 'NoneType' object is not subscriptable

**Comment by erudnick-cohen** [comment] 2021-06-01 23:17
Yup, looks like it. Probably got broken by a change made in the last few updates, thanks for reporting this. This will most likely get fixed when the next version of the item randomizer comes out.

**Comment by Trencha** [comment] 2021-06-17 16:35
I've just come across this same issue using some customised randomiser settings. Upon investigation, it seems to be caused by an extra line that's been accidentally added to the ForceEarlyBike modifier.

**Comment by erudnick-cohen** [comment] 2021-06-28 01:50
This bug is fixed as of the most recent randomizer release (V5)

**Closed by erudnick-cohen** 2021-06-28 01:50 UTC
